filebeat.prospectors:

packetbeat.interfaces.device: any

packetbeat.protocols.icmp:
  enabled: true

packetbeat.protocols.dns:
  ports: [53]

  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 8080, 8081, 5000, 8002]

packetbeat.protocols.memcache:
  ports: [11211]

packetbeat.protocols.mysql:
  ports: [3306]

packetbeat.protocols.pgsql:
  ports: [5432]

packetbeat.protocols.redis:
  ports: [6379]

packetbeat.protocols.thrift:
  ports: [9090]

packetbeat.protocols.mongodb:
  ports: [27017]

packetbeat.protocols.cassandra:
  ports: [9042]

#output.logstash:
#  hosts: ["45.77.102.84:5044"]

output.elasticsearch:
  hosts: ["45.77.102.84:9200"]
