filebeat.prospectors:

- type: log
  enabled: true
  paths:
    - /cowrie/cowrie-git/log/*.log
  tags: ["cowrie-log"]

- type: log
  enabled: true
  paths:
    - /cowrie/cowrie-git/log/*.json
  tags: ["cowrie-json"]

output.logstash:
  hosts: ["79.104.53.14.elk-master:50443"]
  ssl.certificate_authorities: ["/etc/filebeat/logstash.crt"]
  ssl.certificate: "/etc/filebeat/client.crt"
  ssl.key: "/etc/filebeat/client.key"

shipper:
    logging:
    files:
    rotateeverybytes: 10485760 # = 10MB
